In [ ]:
# import library
# veri seti yükle
# tfidf
# kelime kümesi incele
# tfidf skorlarını içeren bir df 
# skorları görselleştir

In [1]:
import numpy as np
import pandas as pd 
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df=pd.read_csv("spam.csv", encoding="latin-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(df["v2"])

In [6]:
feature_names=vectorizer.get_feature_names_out()
print(f"feature names: {feature_names[:10]}")

feature names: ['00' '000' '000pes' '008704050406' '0089' '0121' '01223585236'
 '01223585334' '0125698789' '02']

In [7]:
tfidf_scores=X.mean(axis=0).A1

In [8]:
df_tfidf=pd.DataFrame({"words":feature_names, "tfidf_score":tfidf_scores})
df_tfidf.sort_values("tfidf_score", ascending=False).head(10)

     words  tfidf_score
8609   you     0.044145
7756    to     0.036946
7627   the     0.026384
4087    in     0.021946
4939    me     0.021159
1084   and     0.020217
4206    is     0.019703
4218    it     0.018706
5223    my     0.018602
1813  call     0.017207